### ISSUE TITLE
HLS Watch Implementation

### ISSUE THREAD

**Issue by Craytor** [faryon93/hlswatch#1]
Greetings,

I've been trying to find a way to monitor HLS connections for quite some time; from watching logs and beyond. I came across your project today as I am trying to find another a better way to track viewers. And I think I may have found a way.

I am using Clappr in my scenario as well, so I'm intrigued to test this out on our end. I've read through the documentation and wondering the most straight forward approach to implement this.

On my end I'm currently using nginx-rtmp-module, so I assume that based on your documentation I will have to remove the existing http block and replace it with proxy_pass. From there I have to install the hlswatch project and build it with Go. Then install InfluxDB to the server, verify the environmental settings, and then it should be good to go?

Finally, currently I have my stream urls set as "domain.com/hls/{{streamId}}/index.m3u8" - will this still be compatible, or do I have to do additional configuration to allow for this?

Thank you for your time, I look forward to the direction hlswatch is going!

Thanks,
Tyler

**Comment by Craytor** [comment]
Also, when I do ```docker build .``` I get the following error:
![image](https://cloud.githubusercontent.com/assets/3680866/24021035/3f0216b8-0a75-11e7-82c6-21eed3384b2a.png)

**Comment by faryon93** [comment]
Sorry for my delayed response.

Your assumptions about configuring nginx are right. Delivering the hls playlist and video fragments is handeled by hlswatch, in order to keep track of incoming requests. NGINX justs forwards all HTTP requests to hslwatch (thats why you need the proxy_pass option).

You can use the provided Makefile to build the go application and build the docker container. For a complete build "$: make" should be sufficient. If you just want to build hlswatch and build the docker container yourself use "$: make hlswatch". The docker image contains a minimal nginx example, the used configuration can be found in rootfs/etc/nginx/nginx.conf

**Comment by Craytor** [comment]
Sorry, just saw your message! I'll take a look this evening and see if I can figure it out - thanks!

**Comment by faryon93** [comment]
I just pushed a version which builds the hlswatch binary inside a docker container. Just run:
`$: docker build -t faryon93/hlswatch .`

Edit:
The current version contained in "master" is automatically build by docker hub und published as faryon93/hlswatch. So a simple `$: docker pull faryon93/hlswatch` is sufficient to get the newest version.
